### ISSUE TITLE
New Tinted Theming repo

### ISSUE THREAD

**Issue by JamyGolden** [tinted-theming/base16-waybar#1]
@laenzlinger I've set up the repo and sent an invite to join the tinted-theming org team which maintains this repo. I've also set up a github action to run on these files every sunday (like we have for the other template repos too), so you won't have to manually build with builder-go. I think it would be good for you to be a maintainer just to keep a pulse on this repo in case anyone leaves any PRs (which you could test out) or create any issues. Based on the activity on the other repo I don't expect much to be happening though. I'll make sure to also keep an eye on this repo though :smile:

**Comment by laenzlinger** [comment]
thanks for forking and up the the repo, I have switched my local tinty config to this, and works perfectly now with all the themes.

I am OK to maintain this repo in future. Also don't think there will be very much to be done, as long as the principle stays as it is.

Should I create a PR against https://github.com/tinted-theming/home to switch the docu to this repo?

**Comment by JamyGolden** [comment]
Yeah that would be great if you create a PR for that on tinted-theming/home

**Comment by JamyGolden** [comment]
I'll close this issue now
